name: Update Judul Konten

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update judul setiap 1 menit
      run: |

        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        for i in {1..5}
        do
          echo "Update ke $i"

          curl -sL https://www.bppbola.my.id/home/judul-konten -o page.html

          META=$(grep -oP '(?<=<meta property="og:description" content=").*?(?=")' page.html || true)

          echo "$META" > raw.txt

          echo "[" > judul.json
          awk 'NF{printf "\"%s\",\n",$0}' raw.txt >> judul.json
          sed -i '$ s/,$//' judul.json
          echo "]" >> judul.json

          git add judul.json
          git commit -m "update judul otomatis" || echo "tidak ada perubahan"
          git push || true

          sleep 60
        done
